### ISSUE TITLE
when clicking on a unit, nothing comes up

### ISSUE THREAD

**Issue by rinigus** [a-dekker/sailunit#1]
Hi,

thank you for writing and publishing Sailunit! Great idea and I am looking forward to use it. When I start the application, I get the list of units, as shown on your screenshot. However, none of the units I tried show anything in details (when clicking unit name). 

Device: onyx; SFOS 2.1.0.11

**Comment by a-dekker** [comment]
Hi,

I am afraid it can be related to the systemd version (225+git5-1.15.2 over here, SFOS build 2.1.3.7).

For displaying the unit content, it uses "systemctl cat" (for example systemctl cat basic.target), and I vaguely remember this was not supported on older systemd versions.

**Comment by rinigus** [comment]
Excellent, then its even more initiative to update onyx port :) . I am closing it, maybe just mention in README min SFOS requirements?

**Comment by a-dekker** [comment]
Yep, I will make a note of this.
