### ISSUE TITLE
[Wish] Display reverse dependencies

### ISSUE THREAD

**Issue by Olf0** [a-dekker/sailunit#3]
@a-dekker, the ability to easily display the (forward) dependencies (i.e., which units depend on this unit) at the GUI is a very useful feature of Sailunit for me.
But almost as often I need to see the reverse dependencies (i.e., which units this unit depends on), but have to resort to `systemctl` each time (I hope I did not miss something in Sailunit, which already provides this.).

Hence this suggestion for an enhancement ("wish") is to provide a way to display the reverse dependencies of a systemd unit in Sailunit.

**Comment by a-dekker** [comment]
I guess you are looking for the additional "--reverse" parameter. This is added by commit https://github.com/a-dekker/sailunit/commit/2ed78258180348bc4c08134b8dfe89069f12e93b and in the latest release on openrepos.

**Comment by Olf0** [comment]
Thanks!
